#!/usr/bin/env python
# -*- coding: UTF-8 -*-
version = '2.0'

import cgi
import time as t
import os

form = cgi.FieldStorage()
ClientId = form.getvalue('ClientId', '0000')
SSID = form.getvalue('SSID', '0')
Passkey = form.getvalue('Passkey', '0')
IP = form.getvalue('IP', '0')
IPR = form.getvalue('IPR', '0')

print('Content-type:text/html\r\n\r\n')
print('<html><head><title>')
print('Open Irrigation Software')
print('</title></head>')

print('<style>')
print('h2 {')
print('  display: block;')
print('  background-color: #72AAD8;')
print('  align: left;')
print('  width: 108%;')
print('  margin-top: 0.83em;')
print('  margin-bottom: 0.83em;')
print('  margin-left: -10;')
print('  margin-right: 0;')
print('  padding: 0px;')
print('  position: relative;')
print('  font-weight: bold;')
print('  color: white;')
print('  font-size: 1.5em;')
print('}')
print('h3 {')
print('  display: block;')
print('  align: left;')
print('  margin-top: 0.83em;')
print('  margin-bottom: 0.83em;')
print('  margin-left: 0;')
print('  margin-right: 0;')
print('  padding: 0px;')
print('  position: relative;')
print('  font-weight: bold;')
print('  color: #1671AE;')
print('  font-size: 1.2em;')
print('}')
print('h4 {')
print('  display: block;')
print('  margin-top: 0.83em;')
print('  margin-bottom: 0.83em;')
print('  align: left;')
print('  margin-left: 0;')
print('  margin-right: 0;')
print('  padding: 0px;')
print('  position: relative;')
print('  font-weight: bold;')
print('  color: #4F4F4F;')
print('  font-size: 1.2em;')
print('}')
print('h5 {')
print('  display: block;')
print('  margin-top: 0;')
print('  margin-bottom: 0;')
print('  align: left;')
print('  margin-left: 0;')
print('  margin-right: 0;')
print('  padding: 0px;')
print('  position: relative;')
print('  font-weight: bold;')
print('  color: #4F4F4F;')
print('  font-size: 1.0em;')
print('}')
print('</style>')

print('<body style="margin: 0px; padding: 0px; font-family: arial, sans-serif;">')

print('<table width="100%" style="height: 100%;" cellpadding="10" cellspacing="0" border="0">')
print('<tr>')

print('<!-- ============ HEADER SECTION ============== -->')
print('<table width="100%" cellpadding="10" cellspacing="0" border="0">')
print('<tr>')
print('<td colspan="2" height="80px" bgcolor="#5B7AA7"> ')
print('<font size="5.5" color="#F6DE82" align="left" valign="center"><b>OPEN IRRIGATION</b></font>')
print('</td></tr>')

print('<!-- ============ NAVIGATION BAR SECTION ============== -->')
print('<tr><td colspan="2" valign="middle" height="50" bgcolor="#EBF1FA">')
print('<a href="/index.html" class="StandardButton">HOME</a>')
print('<a href="/gardendata.html" class="StandardButton">SETTINGS</a>')

print('<style media="screen" type="text/css">')
print('.StandardButton {')
print('background-color:#77b55a;')
print('-moz-border-radius:4px;')
print('-webkit-border-radius:4px;')
print('border-radius:4px;')
print('border:1px solid #4b8f29;')
print('display:inline-block;')
print('cursor:pointer;')
print('color:#ffffff;')
print('font-family:Arial;')
print('font-size:12px;')
print('font-weight:bold;')
print('margin: 5px;')
print('padding:10px 16px;')
print('text-decoration:none;')
print('text-shadow:0px 0px 0px #5b8a3c;')
print('}')
print('.StandardButton:hover {')
print('background-color:#72b352;')
print('}')
print('.StandardButton:active {')
print('position:relative;')
print('top:1px;')
print('}')
print('</style>')
print('</td></tr>')

print('<!-- ============ LEFT COLUMN (MENU) ============== -->')
print('<td width="80%" valign="top" bgcolor=#FAFBFB>')
print('<h2>Your settings have been saved</h2>')
print('The irrigation computer will reboot.<br>')
print('Please wait one minute for the initialisation to be completed<br><br>')
print('The IP address of the Irrigation computer is: <a href="http://' + str(IP) + '">', IP, '</a><br><br>')
print('The IP address of the router is: <a href="http://' + str(IPR) + '">', IPR, '</a><br><br>')
print(
    'Your irrigation history and settings can be accessed by entering the IP address in your browsers address bar.<br>')
print(
    'If this was your initial setup, go to the settings page to configure your irrigation system and garden data.<br>')
print(
    'If you had an irrigation computer before, the system will try to download a backup to recover all your data.<br><br>')
print('For support or assistance feel free to contact an Open Irrigation partner in your neighbourhood.<br>')
print(
    'More details about our support can be found at the <a href="https://gitlab.com/jtdaling/OpenIrrigation">Open Irrigation website</a>.')
print('<table>')
print('</table>')

print('<!-- ============ FOOTER SECTION ============== -->')
print('<table width="100%" height="7" bgcolor="#FAFBFB">')
print('<td align="right" >')
print('<font size="2">Open Irrigation version ' + version + '&nbsp;&nbsp;')
print('</font></td>')
print('</table>')
print('</body>')
print('</html>')

# upload data to textfile for use by htmlgenerator
output = open('/OpenIrrigation/network.txt', 'w')
output.write(ClientId + '\n')
output.write(SSID + '\n')
output.write(Passkey + '\n')
output.write(IP + '\n')
output.write(IPR + '\n')
# check if an static ip is configured:
if IP > '0':
	output.write('static\n')
else:
	output.write('dhcp\n')
output.close()



exit()
